"""Compatibility exports for split Phase 2A calibration modules until Stage 11."""

from dai_sim.calibration.data_loading import (
    PROJECT_ROOT,
    load_inputs,
    parse_utc_timestamp,
    phase2a_input_specs,
    require_hourly_index,
    sha256_file,
    validate_protocol_intervals,
    verify_all_inputs,
)
from dai_sim.calibration.gas import calculate_transaction_gas_cost
from dai_sim.calibration.market import (
    CALIBRATION_END_EXCLUSIVE,
    CALIBRATION_START,
    DEFAULT_FIGURES,
    DEFAULT_OUTPUT,
    DEFAULT_REPORT,
    ESTIMABLE_SOURCES,
    FTX_VALIDATION_END_EXCLUSIVE,
    FTX_VALIDATION_START,
    PARAMETER_PLAN,
    PARAMETER_STATUSES,
    REQUIRED_CANDIDATE_FIELDS,
    Phase2AConfig,
    aggregate_liquidation_volume,
    build_parameter_status,
    run_phase2a,
    validate_candidate_registry,
)
from dai_sim.calibration.statistics import (
    aligned_dependence,
    candidate_block_length,
    classify_regimes,
    distribution_summary,
    estimate_regime_thresholds,
    moving_block_bootstrap_ci,
    overdispersion_summary,
    regime_durations,
    transition_counts,
    transition_probabilities,
)

__all__ = [
    "CALIBRATION_END_EXCLUSIVE",
    "CALIBRATION_START",
    "DEFAULT_FIGURES",
    "DEFAULT_OUTPUT",
    "DEFAULT_REPORT",
    "ESTIMABLE_SOURCES",
    "FTX_VALIDATION_END_EXCLUSIVE",
    "FTX_VALIDATION_START",
    "PARAMETER_PLAN",
    "PARAMETER_STATUSES",
    "PROJECT_ROOT",
    "REQUIRED_CANDIDATE_FIELDS",
    "Phase2AConfig",
    "aggregate_liquidation_volume",
    "aligned_dependence",
    "build_parameter_status",
    "calculate_transaction_gas_cost",
    "candidate_block_length",
    "classify_regimes",
    "distribution_summary",
    "estimate_regime_thresholds",
    "load_inputs",
    "moving_block_bootstrap_ci",
    "overdispersion_summary",
    "parse_utc_timestamp",
    "phase2a_input_specs",
    "regime_durations",
    "require_hourly_index",
    "run_phase2a",
    "sha256_file",
    "transition_counts",
    "transition_probabilities",
    "validate_candidate_registry",
    "validate_protocol_intervals",
    "verify_all_inputs",
]
