"""Compatibility exports for split empirical market modules until Stage 11."""

from dai_sim.inputs.market import (
    DEFAULT_CONFIG_PATH,
    DEFAULT_PROCESSED_DATA_DIR,
    EmpiricalConfig,
    build_market_time_panel,
    collect_baseline_configuration_issues,
    empirical_config_from_mapping,
    load_baseline_config,
    load_empirical_config,
)
from dai_sim.calibration.market import (
    BASELINE_OUTPUT_DIR,
    DEFAULT_OUTPUT_DIR,
    EMPIRICAL_OUTPUT_DIR,
    POOL_COLUMNS,
    PROJECT_ROOT,
    SYNTHETIC_FIXTURE_PATH,
    SYNTHETIC_OUTPUT_DIR,
    classify_market_regimes,
    compute_empirical_summary,
    create_regime_conditioned_pools,
    create_sample_overlap_report,
    create_synthetic_fixture_config,
    estimate_regime_thresholds,
    estimate_regime_transition_matrix,
    main,
    run_baseline_empirical_pipeline,
    run_empirical_pipeline,
    run_synthetic_validation,
    write_empirical_outputs,
)
from dai_sim.inputs.sources import (
    CANONICAL_INPUT_COLUMNS,
    MANIFEST_COLUMNS,
    PRICE_COLUMNS,
    REQUIRED_BASELINE_COLUMNS,
    EmpiricalFieldConfig,
    EmpiricalSourceConfig,
    ExplicitUnitConversion,
    adapt_source_frame,
    empirical_source_from_mapping,
    load_and_align_sources,
    validate_data_manifest,
    validate_fixed_frequency,
    validate_manifest_records,
)

__all__ = [
    "BASELINE_OUTPUT_DIR",
    "CANONICAL_INPUT_COLUMNS",
    "DEFAULT_CONFIG_PATH",
    "DEFAULT_OUTPUT_DIR",
    "DEFAULT_PROCESSED_DATA_DIR",
    "EMPIRICAL_OUTPUT_DIR",
    "EmpiricalConfig",
    "EmpiricalFieldConfig",
    "EmpiricalSourceConfig",
    "ExplicitUnitConversion",
    "MANIFEST_COLUMNS",
    "POOL_COLUMNS",
    "PRICE_COLUMNS",
    "PROJECT_ROOT",
    "REQUIRED_BASELINE_COLUMNS",
    "SYNTHETIC_FIXTURE_PATH",
    "SYNTHETIC_OUTPUT_DIR",
    "adapt_source_frame",
    "build_market_time_panel",
    "classify_market_regimes",
    "collect_baseline_configuration_issues",
    "compute_empirical_summary",
    "create_regime_conditioned_pools",
    "create_sample_overlap_report",
    "create_synthetic_fixture_config",
    "empirical_config_from_mapping",
    "empirical_source_from_mapping",
    "estimate_regime_thresholds",
    "estimate_regime_transition_matrix",
    "load_and_align_sources",
    "load_baseline_config",
    "load_empirical_config",
    "main",
    "run_baseline_empirical_pipeline",
    "run_empirical_pipeline",
    "run_synthetic_validation",
    "validate_data_manifest",
    "validate_fixed_frequency",
    "validate_manifest_records",
    "write_empirical_outputs",
]

if __name__ == "__main__":
    main()
